### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by veloxy** [veloxy/haveibeenpwned-cli#2]
[This file](https://github.com/veloxy/haveibeenpwned-cli/blob/master/src/Console/Command/CsvCheckerCommand.php) needs some refactoring, it's currently doing way too much.

**Comment by captbrogers** [comment]
I might be able to help with this, how exactly did you want it refactored? I do have a few ideas on what could be done. Want to assign it to me?

**Comment by veloxy** [comment]
@captbrogers A first iteration has been done, what I eventually thought about doing is [this](https://github.com/veloxy/haveibeenpwned-cli/pull/5#issuecomment-250708090). If you're feeling up for it, give it a shot! If not, I'll do it myself eventually when I have a bit more time for it.

**Comment by ins0** [comment]
i will give it a turn ;D
