### ISSUE TITLE
Create phar file

### ISSUE THREAD

**Issue by veloxy** [veloxy/haveibeenpwned-cli#3]
I was thinking about having a phar file I can just add to a release, so that people can just run it. I briefly looked into it and found [phar composer](https://github.com/clue/phar-composer). 
Other suggestions are welcome!

It could be a script building this, or using an existing tool. Either way, the README has to be updated to add build instructions so a pull request will be needed. That's why I'll add the hacktoberfest label!

**Comment by micheleorselli** [comment]
Hi @veloxy,
may I suggest https://github.com/box-project/box2 for managing phar creation? I've used it extensively for a cli automation tool we use in our company (https://github.com/ideatosrl/Idephix)

I could submit a PR for this to show how it works

**Comment by veloxy** [comment]
@micheleorselli Looks good to me!
